name: Check eligible for Auto Approval

on:
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains('["simonhauck", "renovate[bot]"]', github.actor)
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}